services:
  - type: web
    name: spring-boot-chat
    env: java
    buildCommand: ./mvnw package -DskipTests
    startCommand: java -jar target/*.jar
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: -Xmx256m -Xms128m